# Generated by Django 2.2 on 2019-04-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
