# Generated by Django 2.2 on 2019-04-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_projects_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
